import type { Metadata } from "next";
import { Geist, Geist_Mono ,Suez_One,Space_Mono,Montserrat,Noto_Sans_Georgian} from "next/font/google";
import "./globals.css";
import FooterLI from "./componnets/Foo";
import EnquiryPopup from "./componnets/EnquiryPopup";

const suezOne = Suez_One({
  variable: "--font-suez-one",
  subsets: ["latin"],
  weight: "400",
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: "400",
});

const georgia  =  Noto_Sans_Georgian({
  variable:"--font-moto-sans"
})

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceMono.variable} ${suezOne.variable}  ${montserrat.variable} ${georgia.variable} antialiased bg-background`}
      >
        {children}
        <EnquiryPopup/>
       <FooterLI/>
      </body>
    </html>
  );
}
